#!/usr/bin/env bash
#Installs an nginx web server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" < /var/www/html/index.nginx-debian.html
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
