#!/usr/bin/env bash
# Create a pid file that can be killed only using special interactions

echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"
rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "rm /var/run/holbertonscript.pid;exit" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
