#!/usr/bin/env bash
# A bash script that manages manage_my_process file

path=/var/run/my_process.pid

if [ "$1" = "start" ];then
    ./manage_my_process &
    echo "$$" > $path
    echo "manage_my_process started"
elif [ "$1" = "stop" ];then
    pkill -f ./manage_my_process
    rm $path
    echo 'manage_my_process stopped'
elif [ "$1" = "restart" ];then
     pkill -f ./manage_my_process
     rm $path
     ./manage_my_process &
     echo "$$" > $path
     echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
